### ISSUE TITLE
Update to less 2.3.1 

### ISSUE THREAD

**Issue by volnei** [bertramdev/less-asset-pipeline#1]

**Comment by volnei** [comment]
Less is now in 2.5.0 final and framework still with 1.7.0 =(

**Comment by davydotcom** [comment]
PR's are most welcome

**Comment by volnei** [comment]
ok.. I will submit

**Comment by davydotcom** [comment]
## ty, should just be a matter of swapping out the less.js file in the class path. and bumping the version of less4j

David Estes

On April 6, 2015 at 7:22:49 AM, Volnei Munhoz (notifications@github.com) wrote:

ok.. I will submit

**Comment by volnei** [comment]
@davydotcom I've created the pull request https://github.com/bertramdev/less-asset-pipeline/pull/2 and it's already tested!

thank you

**Comment by davydotcom** [comment]
Merged and published. Please note it may take up to 10 minutes for the core plugin to appear in maven central. It is released as version `2.1.0` . Thanks for the PR!!

**Comment by volnei** [comment]
Thanks =)
