### ISSUE TITLE
Read LESS files from classpath?

### ISSUE THREAD

**Issue by kensiprell** [bertramdev/less-asset-pipeline#4]
David,

I'm working on a Grails 3 [Bootstrap Framework plugin](https://github.com/kensiprell/grails3-bootstrap) with the heavy lifting done in a [gradle plugin](https://github.com/kensiprell/grails3-bootstrap/blob/master/buildSrc/src/main/groovy/grails/plugin/bootstrap/BootstrapGradlePlugin.groovy). I've never used LESS, so now I'm scratching my head and wondering how to make it work with the Grails less-asset-pipeline plugin.

My plugin depends on the WebJars libraries at [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.webjars.bower%22%20a%3A%22bootstrap%22). How do I make the *.less files available to the compiler? Can your plugin read the bytes from the classspath, or do I need to put static files in the `grails-app/assets/sytlesheets` directory? 

Thanks for your help,
Ken

**Comment by davydotcom** [comment]
The plugin should be able to resolve webjars at lease with 2.3.4 version of asset-pipeline-core and asset-pipeline-gradle. However I think you would get a better experience not using webjars since webjars requires the version in the require directive. That being said it should work

**Comment by kensiprell** [comment]
Thanks for the quick response. I decided to go with WebJars so I don't have to fool around with updating files and releasing a plugin update whenever a new Bootstrap version comes out.

For example, a manifest file could have this entry:

```
*= require bootstrap-all
```

And the bootstrap-all.css file looks like this:

```
/*
* Do not edit this file. It will be overwritten by the bootstrap plugin.
*
*= require webjars/bootstrap/3.3.5/dist/css/bootstrap-theme.css
*= require webjars/bootstrap/3.3.5/dist/css/bootstrap.css
*/
```

However, I don't understand how to make the LESS files available to the less-asset-pipline plugin. Is it simply a matter of adding a `grails-app/assets/stylesheets/alerts.less.css` file (example below) that the user adds to a manifest?

```
/*
* Do not edit this file. It will be overwritten by the bootstrap plugin.
*
*= require webjars/bootstrap/3.3.5/less/alerts.less
*= require webjars/bootstrap/3.3.5/less/mixins/alerts.less
*/
```

**Comment by davydotcom** [comment]
Files are resolved in order of the registered resolvers.
Think of the resolvers like a layered file system. Your web jar is lower on the list so all files in a users `grails-app/assets` take precedence. However remember if you want them to override say `alerts.less` they have to make sure their copy of `alerts.less` follows the same directory structure as the file being replaced.

**Comment by kensiprell** [comment]
Thanks, David. It'll probably be the weekend before I'll have chance to work on this again. If I have any more less-asset-pipeline questions, do you mind if I send an email to your gmail address (rather that clutter up your issues page)?
