### ISSUE TITLE
Troubleshooting Less compilation – Grails3

### ISSUE THREAD

**Issue by jesperronn** [bertramdev/less-asset-pipeline#5]
As a first-time user for this plugin I have generated an example project which can show how to set up `build.gradle` for a Grails 3 project.

I was missing some details in the current `README.md` of this plugin, which is reflected in https://github.com/jesperronn/grails3-less/pull/5 

If others have similar problems loading the plugin, then be aware that the plugin should be loaded differently, which you can see of the changes in `build.gradle` here: https://github.com/jesperronn/grails3-less/pull/5/files#diff-c197962302397baf3a4cc36463dce5eaR67

*_NOTE *_ the subtle differences between `buildScript.dependencies` and `dependencies` in the link above 

(not really an issue here, but you can probably label it)

**Comment by jesperronn** [comment]
Reference to original bug description: https://github.com/jesperronn/grails3-less/issues/4

**Comment by davydotcom** [comment]
This should be working wiht grails `asset-pipeline:3.0.8`
